CREATE DATABASE inventorydb;

USE inventorydb;

CREATE TABLE inventorydb.producto (
  SKU INT NOT NULL AUTO_INCREMENT,
  Descripcion VARCHAR(45) NOT NULL,
  Stock INT NOT NULL,
  PRIMARY KEY (SKU));
  
CREATE TABLE inventorydb.orden (
  IdOrden INT NOT NULL AUTO_INCREMENT,
  SKU INT NOT NULL,
  Cantidad INT NOT NULL,
  FechaIngreso DATE NOT NULL,
  Estado VARCHAR(45) NOT NULL,
  PRIMARY KEY (IdOrden));
  
ALTER TABLE inventorydb.orden 
ADD INDEX SKU_idx (SKU ASC) VISIBLE;
;
ALTER TABLE inventorydb.orden 
ADD CONSTRAINT SKU
  FOREIGN KEY (SKU)
  REFERENCES inventorydb.producto (SKU)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/*
INGRESO  +
SALIDA -
ANULACION INGRESO -
ANULACION SALIDA +
*/
DELIMITER //
CREATE PROCEDURE MakeOrders(IN SKU_IN INT, IN CANTIDAD_IN INT, IN STATUS_IN VARCHAR(45))
BEGIN

SET @CANTIDAD_ACTUAL = (SELECT STOCK FROM PRODUCTO WHERE SKU = SKU_IN);
INSERT INTO ORDEN (SKU, CANTIDAD, FECHAINGRESO, ESTADO) VALUES (SKU_IN, CANTIDAD_IN, CURDATE(), STATUS_IN);

IF STATUS_IN = "INGRESO" THEN
	UPDATE PRODUCTO SET STOCK = @CANTIDAD_ACTUAL + CANTIDAD_IN WHERE SKU = SKU_IN;
ELSE
	UPDATE PRODUCTO SET STOCK = @CANTIDAD_ACTUAL - CANTIDAD_IN WHERE SKU = SKU_IN;
END IF;

SELECT * FROM ORDEN WHERE IDORDEN = @@IDENTITY;

END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE ManageOrders(IN IDORDER_IN INT)
BEGIN
SET @CANTIDAD = (SELECT CANTIDAD FROM ORDEN WHERE IDORDEN = IDORDER_IN);
SET @ESTADO_ORDEN = (SELECT ESTADO FROM ORDEN WHERE IDORDEN = IDORDER_IN);
SET @SKU = (SELECT SKU FROM ORDEN WHERE IDORDEN = IDORDER_IN);
SET @CANTIDAD_ACTUAL = (SELECT STOCK FROM PRODUCTO WHERE SKU = @SKU);
SET @ESTADO_SKU= (SELECT CONCAT(@ESTADO_ORDEN,'-',IDORDER_IN) FROM PRODUCTO WHERE SKU = @SKU);

IF @ESTADO_ORDEN = "INGRESO" THEN
	UPDATE PRODUCTO SET STOCK = @CANTIDAD_ACTUAL - @CANTIDAD WHERE SKU = @SKU; 
    UPDATE ORDEN SET ESTADO=CONCAT(@ESTADO_ORDEN,' ','ANULADO') WHERE IdOrden=IDORDER_IN;
    INSERT INTO ORDEN(SKU, CANTIDAD, FECHAINGRESO, ESTADO) VALUES(@SKU, @CANTIDAD, CURDATE(), concat('ANULACIÓN ',@ESTADO_SKU));
ELSEIF  @ESTADO_ORDEN = "SALIDA" THEN
	UPDATE PRODUCTO SET STOCK = @CANTIDAD_ACTUAL + @CANTIDAD WHERE SKU = @SKU; 
    UPDATE ORDEN SET ESTADO=CONCAT(@ESTADO_ORDEN,' ','ANULADA') WHERE IdOrden=IDORDER_IN;
    INSERT INTO ORDEN(SKU, CANTIDAD, FECHAINGRESO, ESTADO) VALUES(@SKU, @CANTIDAD, CURDATE(), concat('ANULACIÓN ',@ESTADO_SKU));
END IF;
SELECT * FROM ORDEN WHERE IDORDEN = @@IDENTITY;

END //
DELIMITER ;


SELECT * FROM ORDEN;
SELECT * FROM PRODUCTO

